name: chitin-demo
hw_version: '0.0.1'
sw_version: '0.0.1'

build_settings:
  processor: 18F57Q43
  programmer: Pickit4
  
  development:
    defines:
      - DEVELOPMENT
      - SHELL_ENABLED
      - SHELL_HISTORY_ENABLED
      - USB_ENABLED
      - LOGGING_ENABLED

  release:
    defines:
      - USB_ENABLED